# Generated by Django 3.2.9 on 2021-11-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='attending_events',
        ),
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(related_name='attending_events', through='levelupapi.EventGamer', to='levelupapi.Gamer'),
        ),
    ]
