# Generated by Django 3.2.9 on 2021-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20211102_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attending',
            new_name='',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
    ]
